### ISSUE TITLE
Configurable bar background & border [Feature Request]

### ISSUE THREAD

**Issue by SendNukez** [i-am-cal/Mojangster#6]
I really like the animated Logo, but i also really like the [Dark Loading Screen](https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen). The bar of the mod looks really good, and i could duplicate that with this mod if i was able to change the bar background & border.

**Comment by i-am-cal** [comment]
Hi! This seems to be your first issue! Please make sure to provide infomation such as logs and version infomation if you are reporting a bug.

**Comment by i-am-cal** [comment]
Planned, will probably implement in 1.5.0, with the animation editor.

**Comment by SendNukez** [comment]
Thank you

**Comment by i-am-cal** [comment]
Added in 2.0.0
